apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: ghcr.io/sosotechnologies/githubwf-build-node-push-to-ecr/node-app:PLACEHOLDER_VERSION
        ports:
        - containerPort: 8088
