apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
images:
  - name: ghcr.io/sosotechnologies/githubwf-build-node-push-to-ecr/node-app
    newTag: PLACEHOLDER_VERSION
