name: Argo CD GitOps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push the image
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Bump version
      id: bump_version
      run: |
        chmod +x build-push-to-gh/bump_version.sh && ./build-push-to-gh/bump_version.sh
        new_version=$(cat VERSION-GH)
        echo "new_version=$new_version" >> $GITHUB_ENV

    - name: Commit new version
      run: |
        git config --global user.name 'sosotechnologies'
        git config --global user.email 'sosotech2000@gmail.com'
        git add VERSION-GH
        git commit -m "Bump version to ${{ env.new_version }}" || echo "No changes to commit"
        git stash
        git pull --rebase origin main
        git stash pop || echo "No stashed changes"
        git push origin main

    - name: Build the Docker image
      run: |
        cd build-push-to-gh
        docker build -t ghcr.io/${{ github.repository }}/node-app:${{ env.new_version }} .

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'ghcr.io/${{ github.repository }}/node-app:${{ env.new_version }}'
        format: 'table'
        exit-code: '0'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'MEDIUM,HIGH,CRITICAL'
        output: 'build-push-to-gh/trivy-report.txt'

    - name: package Trivy report
      uses: actions/upload-artifact@v3
      with:
        name: trivy-report
        path: build-push-to-gh/trivy-report.txt

    - name: Push the Docker image to GitHub Container Registry
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker push ghcr.io/${{ github.repository }}/node-app:${{ env.new_version }}
        docker tag ghcr.io/${{ github.repository }}/node-app:${{ env.new_version }} ghcr.io/${{ github.repository }}/node-app:latest
        docker push ghcr.io/${{ github.repository }}/node-app:latest

  deploy:
    name: Deploy to Argo CD
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Update Kustomize version
      run: |
        new_version=${{ env.new_version }}
        sed -i "s/PLACEHOLDER_VERSION/${new_version}/g kubernetes/kustomization.yaml
        git config --global user.name 'sosotechnologies'
        git config --global user.email 'sosotech2000@gmail.com'
        git add kubernetes/kustomization.yaml
        git commit -m "Update Kustomize version to $new_version" || echo "No changes to commit"
        git pull --rebase origin main
        git push origin main

    - name: Deploy to Argo CD
      run: |
        ARGO_CD_TOKEN=$(curl -s -X POST -H "Content-Type: application/json" -d "{\"username\":\"${{ secrets.ARGO_CD_USERNAME }}\",\"password\":\"${{ secrets.ARGO_CD_PASSWORD }}\"}" https://localhost:8080/api/v1/session | jq -r .token)
        curl -X POST https://localhost:8080/api/v1/applications/node-app/sync \
        -H "Authorization: Bearer $ARGO_CD_TOKEN" \
        -H "Content-Type: application/json" \
        -d '{
              "revision": "main",
              "prune": false,
              "dryRun": false,
              "strategy": {
                "hook": {
                  "force": true
                }
              }
            }'
